<?php

/**
 * @file
 * Contains freely_paragraphs.module.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function freely_paragraphs_theme_suggestions_paragraph_alter(&$suggestions, $variables) {
  $entity = $variables['elements']['#paragraph'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $type = $entity->getType();

  $suggestions[] = 'paragraph__freely_paragraphs';
  $suggestions[] = 'paragraph__freely_paragraphs__' . $type;
  $suggestions[] = 'paragraph__freely_paragraphs__' . $type . '__' . $sanitized_view_mode;
}

/**
 * Implements hook_theme().
 */
function freely_paragraphs_theme() {
  $theme_templates = [];
  $paragraph_types = freely_paragraphs_get_paragraph_types();

  foreach ($paragraph_types as $type) {
    $theme_templates['paragraph__freely_paragraphs__' . $type] = [
      'base hook' => 'paragraph',
    ];
  }

  $theme_templates['paragraph__freely_paragraphs'] = [
    'base hook' => 'paragraph',
  ];

  return $theme_templates;
}

/**
 * Implements hook_theme_registry_alter().
 */
function freely_paragraphs_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'freely_paragraphs');
  $template_objects = drupal_find_theme_templates($theme_registry, '.html.twig', $module_path);
  $paragraph_types = freely_paragraphs_get_paragraph_types();

  /** @var Drupal\Core\Theme\ActiveTheme $active_theme */
  $active_theme = \Drupal::service('theme.manager')->getActiveTheme();
  $theme_path = drupal_get_path('theme', $active_theme->getName());
  $theme_template_objects = drupal_find_theme_templates($theme_registry, '.html.twig', $theme_path);

  if (count($theme_template_objects) > 0) {
    $template_objects = array_merge($template_objects, $theme_template_objects);
  }

  foreach ($paragraph_types as $type) {
    $template = 'paragraph__freely_paragraphs__' . $type;
    // If it doesn't exist, remove it from the registry so
    // we don't get any errors.
    if (!isset($template_objects[$template])) {
      unset($theme_registry['paragraph__freely_paragraphs__' . $type]);
    }
  }
}

/**
 * Get a list of paragraph types by machine name.
 */
function freely_paragraphs_get_paragraph_types() {
  $paragraph_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('paragraph');
  return array_keys($paragraph_bundles);
}
